# Generated by Django 3.0.5 on 2020-04-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'FIRST PLAYER TO MOVE'), ('S', 'SECOND PLAYER TO MOVE'), ('W', 'FIRST PLAYER WINS'), ('L', 'SECOND PLAYER WINS'), ('D', 'DRAW')], default='F', max_length=1),
        ),
    ]
